version: '3'

networks:
  default:
    external:
      name: hangman_network
services:
  web:
    container_name: hanger_game.local
    hostname: hanger_game.local
    image: hangman_game:latest
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ../hangman_project:/code
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - hangman_game.local
